# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI02.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_GuiHand(object):
    def setupUi(self, GuiHand):
        GuiHand.setObjectName(_fromUtf8("GuiHand"))
        GuiHand.resize(1094, 655)
        self.gridLayout_2 = QtGui.QGridLayout(GuiHand)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.line = QtGui.QFrame(GuiHand)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_2.addWidget(self.line, 0, 3, 1, 1)
        self.radioButton_1 = QtGui.QRadioButton(GuiHand)
        self.radioButton_1.setCheckable(True)
        self.radioButton_1.setChecked(True)
        self.radioButton_1.setAutoRepeat(False)
        self.radioButton_1.setObjectName(_fromUtf8("radioButton_1"))
        self.gridLayout_2.addWidget(self.radioButton_1, 1, 0, 1, 2)
        self.plainTextEdit = QtGui.QPlainTextEdit(GuiHand)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit.sizePolicy().hasHeightForWidth())
        self.plainTextEdit.setSizePolicy(sizePolicy)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.gridLayout_2.addWidget(self.plainTextEdit, 1, 3, 2, 1)
        self.graphicsView = QtGui.QGraphicsView(GuiHand)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.gridLayout_2.addWidget(self.graphicsView, 1, 4, 13, 1)
        self.groupBox = QtGui.QGroupBox(GuiHand)
        self.groupBox.setEnabled(True)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setChecked(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.radioButton_a = QtGui.QRadioButton(self.groupBox)
        self.radioButton_a.setEnabled(True)
        self.radioButton_a.setChecked(True)
        self.radioButton_a.setAutoRepeat(False)
        self.radioButton_a.setAutoExclusive(True)
        self.radioButton_a.setObjectName(_fromUtf8("radioButton_a"))
        self.gridLayout.addWidget(self.radioButton_a, 0, 0, 1, 1)
        self.radioButton_b = QtGui.QRadioButton(self.groupBox)
        self.radioButton_b.setEnabled(True)
        self.radioButton_b.setAutoRepeat(False)
        self.radioButton_b.setAutoExclusive(True)
        self.radioButton_b.setObjectName(_fromUtf8("radioButton_b"))
        self.gridLayout.addWidget(self.radioButton_b, 1, 0, 1, 1)
        self.radioButton_c = QtGui.QRadioButton(self.groupBox)
        self.radioButton_c.setEnabled(True)
        self.radioButton_c.setAutoRepeat(False)
        self.radioButton_c.setObjectName(_fromUtf8("radioButton_c"))
        self.gridLayout.addWidget(self.radioButton_c, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 2, 0, 1, 1)
        self.spinBox = QtGui.QSpinBox(GuiHand)
        self.spinBox.setEnabled(False)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.gridLayout_2.addWidget(self.spinBox, 4, 2, 1, 1)
        self.comboBox = QtGui.QComboBox(GuiHand)
        self.comboBox.setEnabled(True)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBox, 3, 0, 1, 2)
        self.label_2 = QtGui.QLabel(GuiHand)
        self.label_2.setEnabled(False)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 4, 0, 1, 1)
        self.label_4 = QtGui.QLabel(GuiHand)
        self.label_4.setEnabled(False)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 5, 0, 1, 1)
        self.spinBox_3 = QtGui.QSpinBox(GuiHand)
        self.spinBox_3.setEnabled(False)
        self.spinBox_3.setObjectName(_fromUtf8("spinBox_3"))
        self.gridLayout_2.addWidget(self.spinBox_3, 6, 2, 1, 1)
        self.spinBox_2 = QtGui.QSpinBox(GuiHand)
        self.spinBox_2.setEnabled(False)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.gridLayout_2.addWidget(self.spinBox_2, 5, 2, 1, 1)
        self.label_5 = QtGui.QLabel(GuiHand)
        self.label_5.setEnabled(False)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 6, 0, 1, 1)
        self.spinBox_4 = QtGui.QSpinBox(GuiHand)
        self.spinBox_4.setEnabled(False)
        self.spinBox_4.setObjectName(_fromUtf8("spinBox_4"))
        self.gridLayout_2.addWidget(self.spinBox_4, 7, 2, 1, 1)
        self.label_6 = QtGui.QLabel(GuiHand)
        self.label_6.setEnabled(False)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 7, 0, 1, 1)
        self.spinBox_5 = QtGui.QSpinBox(GuiHand)
        self.spinBox_5.setEnabled(False)
        self.spinBox_5.setObjectName(_fromUtf8("spinBox_5"))
        self.gridLayout_2.addWidget(self.spinBox_5, 8, 2, 1, 1)
        self.label_7 = QtGui.QLabel(GuiHand)
        self.label_7.setEnabled(False)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 8, 0, 1, 1)
        self.radioButton_2 = QtGui.QRadioButton(GuiHand)
        self.radioButton_2.setCheckable(True)
        self.radioButton_2.setChecked(False)
        self.radioButton_2.setAutoRepeat(False)
        self.radioButton_2.setAutoExclusive(True)
        self.radioButton_2.setAutoRepeatDelay(0)
        self.radioButton_2.setAutoRepeatInterval(0)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.gridLayout_2.addWidget(self.radioButton_2, 9, 0, 1, 2)
        self.plainTextEdit_2 = QtGui.QPlainTextEdit(GuiHand)
        self.plainTextEdit_2.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_2.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_2.setSizePolicy(sizePolicy)
        self.plainTextEdit_2.setObjectName(_fromUtf8("plainTextEdit_2"))
        self.gridLayout_2.addWidget(self.plainTextEdit_2, 9, 3, 1, 1)
        self.label_3 = QtGui.QLabel(GuiHand)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 10, 0, 1, 2)
        self.label = QtGui.QLabel(GuiHand)
        self.label.setText(_fromUtf8(""))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 10, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 193, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 12, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton = QtGui.QPushButton(GuiHand)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Icons/Test-512.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(41, 41))
        self.pushButton.setCheckable(False)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout.addWidget(self.pushButton)
        self.gridLayout_2.addLayout(self.horizontalLayout, 13, 0, 1, 1)
        self.label_8 = QtGui.QLabel(GuiHand)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 11, 0, 1, 1)
        self.checkBoxOpt = QtGui.QCheckBox(GuiHand)
        self.checkBoxOpt.setChecked(False)
        self.checkBoxOpt.setObjectName(_fromUtf8("checkBoxOpt"))
        self.gridLayout_2.addWidget(self.checkBoxOpt, 3, 3, 1, 1)
        self.label_info = QtGui.QLabel(GuiHand)
        self.label_info.setText(_fromUtf8(""))
        self.label_info.setTextFormat(QtCore.Qt.RichText)
        self.label_info.setObjectName(_fromUtf8("label_info"))
        self.gridLayout_2.addWidget(self.label_info, 11, 3, 1, 1)

        self.retranslateUi(GuiHand)
        QtCore.QMetaObject.connectSlotsByName(GuiHand)
        GuiHand.setTabOrder(self.radioButton_1, self.radioButton_2)
        GuiHand.setTabOrder(self.radioButton_2, self.comboBox)
        GuiHand.setTabOrder(self.comboBox, self.spinBox)
        GuiHand.setTabOrder(self.spinBox, self.plainTextEdit)
        GuiHand.setTabOrder(self.plainTextEdit, self.graphicsView)
        GuiHand.setTabOrder(self.graphicsView, self.pushButton)

    def retranslateUi(self, GuiHand):
        GuiHand.setWindowTitle(_translate("GuiHand", "Visualization of Scheduling Algorithms", None))
        self.radioButton_1.setText(_translate("GuiHand", "Sch&eduling Algorithms", None))
        self.radioButton_a.setText(_translate("GuiHand", "&ASAP", None))
        self.radioButton_b.setText(_translate("GuiHand", "A&LAP", None))
        self.radioButton_c.setText(_translate("GuiHand", "&Hu", None))
        self.comboBox.setItemText(0, _translate("GuiHand", "Unconstrained", None))
        self.comboBox.setItemText(1, _translate("GuiHand", "Time constrained", None))
        self.comboBox.setItemText(2, _translate("GuiHand", "Resource constrained", None))
        self.label_2.setText(_translate("GuiHand", "Numbers of Clk:", None))
        self.label_4.setText(_translate("GuiHand", "Units of Adders", None))
        self.label_5.setText(_translate("GuiHand", "Units of Substrators", None))
        self.label_6.setText(_translate("GuiHand", "Units of Multipliers", None))
        self.label_7.setText(_translate("GuiHand", "Units of Divisions", None))
        self.radioButton_2.setText(_translate("GuiHand", "O&perations per Cycle", None))
        self.label_3.setText(_translate("GuiHand", "Summary of operations:", None))
        self.pushButton.setText(_translate("GuiHand", "&Run", None))
        self.label_8.setText(_translate("GuiHand", "Info about Scheduling:", None))
        self.checkBoxOpt.setText(_translate("GuiHand", "Optimization", None))

